name: Auto merge workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    
    steps:
      - name: Merge on 2 approvals
      - uses: pullreminders/label-when-approved-action@main
        env:
          APPROVALS: "2"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
      
